### ISSUE TITLE
Memory buffer overlimit

### ISSUE THREAD

**Issue by surajnarwade** [aws/amazon-kinesis-streams-for-fluent-bit#138]
I can see the following errors on the fluentbit pod:

```
time="2021-05-26T08:20:23Z" level=warning msg="[kinesis 0] 126/500 records failed to be delivered. Will retry.\n"
time="2021-05-26T08:20:23Z" level=warning msg="[kinesis 0] Throughput limits for the stream may have been exceeded."
time="2021-05-26T08:20:24Z" level=warning msg="[kinesis 0] 250/500 records failed to be delivered. Will retry.\n"
time="2021-05-26T08:20:24Z" level=warning msg="[kinesis 0] Throughput limits for the stream may have been exceeded."
time="2021-05-26T08:20:24Z" level=warning msg="[kinesis 0] 251/500 records failed to be delivered. Will retry.\n"
time="2021-05-26T08:20:24Z" level=warning msg="[kinesis 0] Throughput limits for the stream may have been exceeded."
[2021/05/26 08:20:24] [ warn] [engine] failed to flush chunk '1-1622017223.71189057.flb', retry in 9 seconds: task_id=0, input=tail.0 > output=kinesis.0 (out_id=0)
...
...
[2021/05/26 08:20:25] [ info] [input] tail.0 resume (mem buf overlimit)
[2021/05/26 08:20:25] [ warn] [input] tail.0 paused (mem buf overlimit)
[2021/05/26 08:20:26] [ info] [input] tail.0 resume (mem buf overlimit)
```

does that mean I need to increase the number of shards in the kinesis stream? if so is there any metric/alerts I can set in fluentbit when this situation occurs?

**Comment by zhonghui12** [comment]
Hi @surajnarwade,

`Throughput limits for the stream may have been exceeded` log means your request rate is too high. You are sending more logs than your kinesis stream can handle and you need to increase the number of shards in kinesis to increase the throughput that it can handle.

The reason why there is `mem buf overlimit` is because of the throttling. Since fluent bit gets throttled, this leads to retries, which means it is buffering the logs, which leads to the buffer memory being overflowed.

You can check your current `mem_buf_limit` and maybe you should consider increasing it to deal with spikes in log throughput.

**Comment by zhonghui12** [comment]
Close this issue for no reply for almost one month. Please feel free to reopen it if you have more problems. Thanks.
