### ISSUE TITLE
Uneven distribution of records across stream shards

### ISSUE THREAD

**Issue by avst-dmartino** [aws/amazon-kinesis-streams-for-fluent-bit#175]
It seems we have observed uneven distribution of records across our kinesis shards. We are using the latest version -> public.ecr.aws/aws-observability/aws-for-fluent-bit:2.20.0

We are not specifying the partition key so we are letting the plugin generate the partition key for us.

Here is a screenshot from cloud watch of our incoming records metric

 ![incoming records cloud watch metric](https://i.imgur.com/wCt1tsi.png)
 ![incoming records cloud watch metrics](https://i.imgur.com/OqngfME.png)

**Comment by zhonghui12** [comment]
Hi @avst-dmartino, thanks for your reporting but from what you reported, I couldn't find a bug/issue in this behavior. In kinesis, we could not expect a perfectly even distribution across shards with random partition key. More records could help to make the distribution more even but with a small number, you might see what you posted in your metrics.

**Comment by avst-dmartino** [comment]
Hi @zhonghui12 thanks for the response. We also found the same with high volumes. 

![high volume incoming records cloud watch metric](https://i.imgur.com/CqqNLVh.png)

We have recently forked and changed the utility function to generate a random UUID and the issue has gone away. See below. 

![high volume incoming records cloud watch metric, uuid partition key](https://i.imgur.com/FyWvafw.png)

We are running Fluentbit in ECS as a sidecar.

**Comment by zhonghui12** [comment]
Hi @avst-dmartino, thanks for your exploration. Would you like to share your solution with us? I would be appreciated to see if we could improve our code then.

**Comment by dragosmc** [comment]
Hi @zhonghui12, I've been working with @avst-dmartino on this and we're soon going to share what we've done to improve this, but here's a quick rundown:
* we've changed the random generator function to return UUID v4
* we've allowed the consumer of this plugin to specify the batch size of the PutRecords (our theory is that if all our services send 500 events in a batch, even if they're as evenly distributed as they can be, the slight variation in the distribution can influence individual shards because of the amount of data thrown at them - still trying to prove this in a more scientific way other than anecdotal evidence)

Moreover, we're still trying to see the impact on the CPU of generating UUID v4 for every record, but so far we did not see a substantial increase in consumption for our sidecar container.

**Comment by zhonghui12** [comment]
Thanks a lot @dragosmc

**Comment by zhonghui12** [comment]
Hi @avst-dmartino and @dragosmc , is there any update on this issue?

**Comment by zhonghui12** [comment]
Hi @avst-dmartino and @dragosmc,

I am going to close this issue for now as there is no response for a while. Please feel free to reopen it if there is any new finding. Thanks.
