### ISSUE TITLE
How to balance log to predefined shards ?

### ISSUE THREAD

**Issue by jsarkar** [aws/amazon-kinesis-streams-for-fluent-bit#19]
I am planning to use amazon kinesis streams for fluent bit to push the application logs to kinesis. But I am currently stuck as our current Kinesis data stream have predefined shard(s) instead of accepting container_id as shards name.
My above ask also raise another interesting issue, How I can load balance during the streaming from fluentbit if I have multiple shards?

any help on this will be appreciated

**Comment by hossain-rayhan** [comment]
Hi @jsarkar, we can always use our existing Kinesis Data Stream with pre-defined shards. From my understanding, we don't need to set container_id as shard name. Rather, we can set partition_key to group our logs and direct them to different shards. For example, if we set container_id as partition_key, logs generated from different containers will be directed to different shards. Then we can write custom consumer applications to grab logs and store them in our desired destinations. 

Regarding the load-balance, every shard has a throughput limit (1000 records per second for write). Based upon our need, we can increase or decrease the number of shards of our data stream. If we don't mention a partition key, a random one will be generated and logs will be stored in random shards (out of order).

Please let me know if that doesn't answer your question.

**Comment by jsarkar** [comment]
Hi @hossain-rayhan  thank for your reply. I guess, I am still not very clear. Could you please share more details how I can use pre-defined shards with kinesis fluentbit plugin? May be I am missing something, but I don't see any option to mention multiple shards, if I use `kinesis` as output in my fluent bit config file .

**Comment by hossain-rayhan** [comment]
```
[OUTPUT]
    Name            kinesis
    Match           *
    region          us-west-2
    stream          my-kinesis-stream-name
    partition_key   container_id
    append_newline  true
```

Hi @jsarkar , consider the above output configuration which I took from our README file. We just mentioned the stream name `my-kinesis-stream-name` which is already created by the user with proper shard configuration. 

If we do not provide a value for the `partition_key` field, logs will be distributed among existing shards (and possibly equally). 

If we set a value for the `partition_key`, logs will be grouped based upon that key and directed to different shards. The partition_key (container_id) is used to distribute load between shards- but it is not the actual name/ID of a shard. The backend hashes it and uses the hash value to pick a shard.

**Comment by jsarkar** [comment]
Hi @hossain-rayhan thanks for your detailed explanation.I was confused from example and explanation in README regarding partition key and shard id. 
for my specific use case, I have set of predefined partition key. Can I have them listed mention list as like :

```
partition_key   [partition_key, partition_key2, partition_key3]
```

**Comment by PettitWesley** [comment]
@jsarkar There is no support for mentioning a list of keys- that's not how that config option works.

The field `partition_key` is a key in your log message that will be used as the partition key. This value will be present in PutRecords request, and then the kinesis back end will c[ompute an MD5 hash on it to map it to an actual shard in your stream](https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html#partition-key).

Let's walk through this is in an example. All logs ingested into Fluent Bit will be JSON; typically the actual log line emitted by your app will be inside a "log" key. For example, if your app is in an container, Fluent Bit might ingest a log like this:

```
{
    "source": "stdout",
    "log": "116.82.105.169 - Homenick7462 197 [2018-11-27T21:53:38Z] \"HEAD /enable/relationships/cross-platform/partnerships\" 501 13886",
    "container_id": "e54cccfac2b87417f71877907f67879068420042828067ae0867e60a63529d35",
    "container_name": "/ecs-demo-6-container2-a4eafbb3d4c7f1e16e00"
}
```

You can use this plugin to send this log to Kinesis. Let's say you use @hossain-rayhan's example config and set `partition_key` to `container_id`. Then a PutRecords request will be made to your kinesis stream with a record that looks like this:

```
{
   "Records": [ 
      { 
         "Data": --the raw JSON event shown above, serialized--,
         "PartitionKey": "e54cccfac2b87417f71877907f67879068420042828067ae0867e60a63529d35"
      }
   ],
   "StreamName": "my-kinesis-stream-name"
}
```

Notice that the partition key is the container ID shown in the log record above. The Kinesis API will take this value, hash it, and then map it to an actual shard in your stream. This leads to a key thing- **with this plugin there is no way to map a log record to a specific shard.** 

If you need to do that- you would have to make a request to Kinesis yourself using the [ExplicitHashKey](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecordsRequestEntry.html#Streams-Type-PutRecordsRequestEntry-ExplicitHashKey) field which will allow you to explicitly define which shard is used. That is not supported by this plugin.

However, that is because for almost every use case, ExplicitHashKey is not needed. Kinesis users are not supposed to try to map records to specific shards themselves. Instead, you just need to distribute your records between shards for high throughput. This plugin will do that.

If you do not specify `partition_key`, then the plugin will compute a random one- **which means your logs will be randomly balanced between shards**.

**Comment by PettitWesley** [comment]
@jsarkar To answer the question you raised in the issue:

> How I can load balance during the streaming from fluentbit if I have multiple shards?

This plugin will automatically do that. As I explained above, you do not even need to use the `partition_key` field.

This config will load balance logs between all your shards:

```
[OUTPUT]
    Name            kinesis
    Match           *
    region          us-west-2
    stream          my-kinesis-stream-name
```

**Comment by jsarkar** [comment]
@PettitWesley Thanks for the explanation. I have some misunderstanding about `specific shard` and partition key. I am really looking for options where I can inject customized Partition key.

**Comment by PettitWesley** [comment]
> I am really looking for options where I can inject customized Partition key.

Injecting a custom partition key is a solution- not a problem. What is the problem that you're trying to solve? What will custom partition keys help you achieve/solve?

Once I understand that, I can help you understand how to use this tool (or another tool) to achieve your goal.

**Comment by jsarkar** [comment]
I am planning to use this as daemon set in Kubernetes. I am planning to use this specific implementation as we use kinesis stream to pump the log stream to ELK

**Comment by hossain-rayhan** [comment]
Hi @jsarkar ,
I think we discussed the distribution of logs across multiple shards and the way of achieving it. However, regarding other questions, we will appreciate if you consider crating a new issue with description. 

I am closing this issue. Thanks, and feel free to re-open if you are still looking for answers.
